---
- name: Install FreeIPA client package (RHEL)
  dnf:
    name: ipa-client
  when: ansible_os_family == "RedHat"

- name: Install FreeIPA client package (Debian)
  apt:
    name: freeipa-client
  when: ansible_os_family == "Debian"