- name: Enable the nvidia network repo
  ansible.builtin.command:
    cmd: dnf -y config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
  become: true

- name: Install the NVIDIA driver (DKMS included)
  ansible.builtin.dnf:
    name:
      - nvidia-driver
      - nvidia-settings
    state: present
  become: true

# Optional reboot if you need the driver active before CUDA toolkit install
- name: Reboot after driver install
  ansible.builtin.reboot:
    msg: "Rebooting to load NVIDIA kernel modules"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true

- name: Install the CUDA toolkit
  ansible.builtin.dnf:
    name: cuda-toolkit
    state: present
  become: true

- name: Install GPUDirect Filesystem
  ansible.builtin.dnf:
    name: nvidia-gds
    state: present
  become: true

- name: Configure NVIDIA container toolkit repo
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
    dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
  become: true

- name: Install the NVIDIA Container Toolkit
  ansible.builtin.dnf:
    name: nvidia-container-toolkit
    state: present
    lock_timeout: 60
  become: true

- name: Configure container runtime
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=containerd
  become: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true
