---
- name: Enable the nvidia network repo
  shell: >-
    dnf -y config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
  become: true
  
- name: Install the nvidia driver
  shell: >-
    dnf -y install nvidia-driver nvidia-settings
  become: true

# need to restart here??

- name: Install the CUDA toolkit
  shell: >-
    dnf -y install cuda-toolkit
  become: true

- name: Install GPUDirect Filesystem
  shell: >-
    dnf -y install nvidia-gds
  become: true

- name: Symlink ldconfig
  shell: >-
    ln -s /sbin/ldconfig /sbin/ldconfig.real
  become: true

- name: Configure the production repository
  shell: >-
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
    tee /etc/yum.repos.d/nvidia-container-toolkit.repo
  become: true

- name: Install the NVIDIA Container Toolkit
  yum:
    name: nvidia-container-toolkit
    state: present
    lock_timeout: 60

- name: Configure the container runtime
  shell: >-
    nvidia-ctk runtime configure --runtime=containerd
  become: true

- name: Restart containerd
  shell: >-
    systemctl restart containerd
  become: true

- name: Disable udev rule - cp
  shell: >-
    cp /lib/udev/rules.d/40-redhat.rules /etc/udev/rules.d
  become: true

- name: Disable udev rule - sed
  shell: >-
    sed -i 's/SUBSYSTEM!="memory",.*GOTO="memory_hotplug_end"/SUBSYSTEM=="*", GOTO="memory_hotplug_end"/' /etc/udev/rules.d/40-redhat.rules
  become: true

- name: Install nvidia-dkms version {{ nvidia_driver_version }}
  shell: >-
    dkms install -m nvidia -v {{ nvidia_driver_version }}
  become: true

# - name: Modprobe nvidia-dkms module
#   shell: >-
#     modprobe nvidia
#   become: true

- name: Persist nvidia-dkms the module at boot
  shell: >-
    echo "nvidia" >> /etc/modules-load.d/nvidia.conf
  become: true