---
- name: Reload systemd
  systemd_service:
    daemon_reload: true
  listen: Restart crio

- name: Reload crio
  service:
    name: crio
    state: restarted
    enabled: true
  listen: Restart crio