extra_repos:
  - name: nesi-slurm
    file: nesi-slurm
    description: "SLURM Packages built by NeSI"
    baseurl: "https://prod-pulp.hpc.nesi.org.nz/pulp/content/nesi-slurm/"
    gpgcheck: false

slurm_version: 24.11.5

slurm_packages:
  - slurm-sackd-{{ slurm_version }}-1.nesi.el9
  - munge

sackd_options:
  - "--conf-server slurmcontrol"
  # - "--debug"
  # - "--log-file /var/log/sackd.log"